# spring.application.name=gestionEmployerBackend
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_employes
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
